
# This file is automatically generated, you probably don't want to edit this

anovaOneWOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "anovaOneWOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package='moretests',
                name='anovaOneW',
                requiresData=FALSE,
                ...)


        }),
    active = list(),
    private = list()
)

anovaOneWResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="anovaOneW")}))

anovaOneWBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "anovaOneWBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'moretests',
                name = 'anovaOneW',
                version = c(1,0,0),
                options = options,
                results = anovaOneWResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))
