
# This file is automatically generated, you probably don't want to edit this

linRegOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linRegOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="moretests",
                name="linReg",
                requiresData=FALSE,
                ...)


        }),
    active = list(),
    private = list()
)

linRegResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linRegResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="linReg")}))

linRegBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linRegBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "moretests",
                name = "linReg",
                version = c(1,0,0),
                options = options,
                results = linRegResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

